version: "3"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    environment:
      - DEFAULT_HOST=meet.centropiaggio.unipi.it
    ports:
      - 80:80
      - 443:443
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy" # Label needed for Let's Encrypt companion container
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro

  # letsencrypt:
  #   image: nginxproxy/acme-companion
  #   container_name: nginx-proxy-le
  #   volumes_from:
  #     - nginx-proxy
  #   volumes:
  #     - certs:/etc/nginx/certs:rw
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #   restart: always

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: proxy-letsencrypt
    restart: always
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - DEFAULT_EMAIL=salvatore.balestrino@gmail.com
      - NGINX_PROXY_CONTAINER=proxy-nginx
      #- NGINX_DOCKER_GEN_CONTAINER=proxy-dockergen

  app:
    image: react-meeting-room
    environment:
      - LETSENCRYPT_HOST=meet.centropiaggio.unipi.it
      - LETSENCRYPT_EMAIL=salvatore.balestrino@gmail.com
      - VIRTUAL_HOST=meet.centropiaggio.unipi.it
    # volumes:
    #   - ./index.html:/usr/share/nginx/html/index.html

networks:
  default:
    external:
      name: nginx-proxy

volumes:
  conf:
  certs:
  vhost:
  html:
